name: Update Weather, Calculate SMD, and Forecast Alerts 

on:
 schedule:
 # min / hour / day / month / day of week
 # target execution time: 09:30 Ireland Local Time
 - cron: '30 8 * * *' # UTC
 workflow_dispatch: # allows manual triggering of the workflow
  inputs:
   run_target:
    description: demo
    required: true
    default: 'both'
    type: choice
    options:
     - both
     - forecast_only
     - obs_only
 
jobs:
 build:
  runs-on: ubuntu-latest # uses Ubuntu virtual machine provided by Github

  steps:
  - name: Clone the repo onto the runner
    uses: actions/checkout@v3

  - name: Set up Python
    uses: actions/setup-python@v4
    with:
     python-version: '3.11'

  - name: Install Dependencies
    run: |
     python -m pip install --upgrade pip
     pip install pymysql cryptography
     pip install -r backend/requirements.txt

  - name: Run Observation & SMD Calculation
    if: ${{ github.event_name == 'schedule' || github.event.inputs.run_target == 'both' || github.event.inputs.run_target == 'obs_only'}}
    env: 
      DATABASE_URL: ${{secrets.DATABASE_URL}}
    run: python backend/main.py obs

  - name: Run Forecast and Alert Check
    if: ${{ github.event_name == 'schedule' || github.event.inputs.run_target == 'both' || github.event.inputs.run_target == 'forecast_only'}}
    env:
      DATABASE_URL: ${{secrets.DATABASE_URL}}
      EMAIL: ${{secrets.EMAIL}}
      EMAIL_PW: ${{secrets.EMAIL_PW}}
    run: python backend/main.py forecast
